import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      {/*nav for desktop*/}
        <nav className="hidden md:flex text-white p-4 sticky top-0 z-50 backdrop-blur-md bg-zinc-950/40">
              <a href="/" className="hover:underline">
                Home
                </a>

          <ul className="flex ml-auto gap-6">
            <li>
              <a href="/about" className="hover:underline">
                About
              </a>
            </li>
            <li>
              <a href="/garage" className="hover:underline">
                Garage
              </a>
            </li>
            <li>
              <a href="/join" className="hover:underline">
                Join Us
              </a>
            </li>
            <li>
              <a href="/partnership" className="hover:underline">
                Partnership
              </a>
            </li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  );
}
